### ISSUE TITLE
setting custom domain not working

### ISSUE THREAD

**Issue by 66nidhi** [pahud/lambda-gin-refarch#1]
Hello @pahud ,
  I have forked this repo and successfully deployed my APIs to AWS api gateway. It's working gracefully with AWS generated URLs, but I am facing issue while assigning a custom domain to that urls, It's giving me **404 page not found error** How can I set it? can you please draw me? 

 I have already tried by assigning custom domain to individual API for testing, but can't do it in case of multiple APIs(proxy+). Please help me out . Thanks in advance.

Here is **AWS URL** for ex.,
  https://rdk3rfz7ol.execute-api.eu-central-1.amazonaws.com/Prod/ping

How can I set it to use,
  https://futurepath.com/v1/ping

**Comment by pahud** [comment]
I'll look into it later today. Thanks.

**Comment by pahud** [comment]
@66nidhi 

After my investigation, if you define `/v1` for as the path for base path mapping of your custom domain name , your Gin will receive `/v1/ping` instead of `/ping` and you have to define this path in your Gin routerEngine other wise it will simply return 404.

<img width="1180" alt="圖片" src="https://user-images.githubusercontent.com/278432/74813154-cad8de00-532f-11ea-9e56-5e6446f9ddcf.png">


If you remove `/v1` from the base path mapping, you should receive the response.

<img width="414" alt="圖片" src="https://user-images.githubusercontent.com/278432/74813115-b5fc4a80-532f-11ea-96ca-d985fb398f4b.png">




<img width="888" alt="圖片" src="https://user-images.githubusercontent.com/278432/74812975-69187400-532f-11ea-9abc-960db87610dc.png">


Please note Amazon API Gateway will always return `healthy` when you request /ping on its domain name you you can try other path as the screenshot above.

**Comment by 66nidhi** [comment]
@pahud 

Thanks for lightening it, fixed problem.
